version: '3.8'
services: 
  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    privileged: true
    user: root
    volumes:
      - ./jenkins:/app
    ports:
      - "8080:8080"
      - "50000:50000"

networks:
  mynetwork: 